apiVersion: v1
kind: Service
metadata:
  name: pvc-admission-controller
  namespace: pvc-admission-controller
spec:
  selector:
    app: pvc-admission-controller
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
