apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pvc-admission-controller
  annotations:
    cert-manager.io/inject-ca-from: pvc-admission-controller/pvc-admission-controller-certs
webhooks:
  - name: pvc-admission-controller.pvc-admission-controller.svc.cluster.local
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - persistentvolumeclaims
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: pvc-admission-controller
        namespace: pvc-admission-controller
        path: "/validate"
      caBundle: Cg==